---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Karsten Schuldt"
- "Ben Kaden"
title: "Anmerkungen zur Geschichte der Frage: „Was ist Bibliothekswissenschaft“"
subtitle: "Einführung in die historische Abteilung"
pdf: "master.pdf"
date: 2018-11-10
comments: false
sharing: true
footer: true

---