---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Vanessa Nagel"
title: "Feel the Elements"
subtitle: "Im Rahmen des 11. BibCamps 2018 in Hamburg wurden neue Ideen rund um das
Bibliothekswesen gesät und weiterentwickelt"
pdf: "master.pdf"
date: 2018-11-10
comments: false
sharing: true
footer: true

---