---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #34: 90 Jahre Bibliotheks*wissenschaft in Berlin"
urn: "urn:nbn:de:kobv:11-110-18452/20344-3"
date: 2018-10-11 20:00
comments: false
sharing: true
footer: true

---