---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Fritz Milkau"
title: "Zur Einführung [Handbuch der Bibliothekswissenschaft, Erster Band, 1931]"
pdf: "master.pdf"
date: 2018-11-10
comments: false
sharing: true
footer: true

---