---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Fritz Milkau"
title: "Zur Einführung [Handbuch der Bibliothekswissenschaft, Erster Band, 1931]"
urn: "urn:nbn:de:kobv:11-110-18452/20332-5"
date: 2018-11-10
comments: false
sharing: true
footer: true

---