---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Ben Kaden"
- "Linda Freyberg"
- "Karsten Schuldt"
title: "Die wechselhafte Geschichte des Gebäudes der Berliner Bibliothekswissenschaft und seiner Umgebung - eine (unvollständige) Recherche"
urn: "urn:nbn:de:kobv:11-110-18452/20342-1"
date: 2018-11-10
comments: false
sharing: true
footer: true

---