---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Konrad Umlauf" 
- "Sigrid Pohl †"
title: "Eine kurze Geschichte von Buch und Buchhandel"
urn: "urn:nbn:de:kobv:11-110-18452/20325-7"
date: 2018-11-10
comments: false
sharing: true
footer: true

---