---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Thomas Roesnick (Interviewer)"
- "Miriam Brauer (Transkription und Korrektur)"
- "Andreas Erbe (Transkription und Korrektur)"
title: "Interview mit Gertrud Pannier"
pdf: "master.pdf"
date: 2018-11-10
comments: false
sharing: true
footer: true

---