---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Annemarie Vita"
- "Felicitas H채rting"
title: "Das Studium am IBI in der Gegenwart"
subtitle: "Eindr체cke von Bachelor- und Master-Studierenden sowie frisch gebackenen Alumni"
abstract: "Fragenentwicklung: Gesamtes Projektteam. Durchf체hrung, Auswertung und Korrektur: Annemarie Vita, Felicitas H채rting"
urn: "urn:nbn:de:kobv:11-110-18452/20337-5"
date: 2018-11-10
comments: false
sharing: true
footer: true

---