---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Wolfram Horstmann"
title: "Der vorausgeworfene Schatten des Professor Dziatzko"
urn: "urn:nbn:de:kobv:11-110-18452/20343-7"
date: 2018-11-10
comments: false
sharing: true
footer: true

---