
---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Thomas Roesnick (Interviewer)"
- "Felicitas Härting (Transkription und Korrektur)"
- "Miriam Brauer (Transkription und Korrektur)"
title: "Interview mit Vivien Petras und Elke Greifeneder"
pdf: "master.pdf"
date: 2018-11-10
comments: false
sharing: true
footer: true

---
