---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Georg Leidinger"
title: "Was ist Bibliothekswissenschaft"
pdf: "../master.pdf"
date: 2018-11
comments: false
sharing: true
footer: true

---