---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Georg Leidinger"
title: "Was ist Bibliothekswissenschaft"
urn: "urn:nbn:de:kobv:11-110-18452/20330-4"
date: 2018-11-10
comments: false
sharing: true
footer: true

---