---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Kirsten Schlebbe (Interviewerin)"
title: "Interview mit Engelbert Plassmann"
urn: "urn:nbn:de:kobv:11-110-18452/20334-7"
date: 2018-11-10
comments: false
sharing: true
footer: true

---