---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Kirsten Schlebbe (Interviewerin)"
title: "Interview mit Engelbert Plassmann"
pdf: "master.pdf"
date: 2018-11-10
comments: false
sharing: true
footer: true

---