---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #3 (Sommer / Herbst 2018)"
urn: "urn:nbn:de:kobv:11-110-18452/20323-6"
date: 2018-10-11 20:00
comments: false
sharing: true
footer: true

---