---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Vera Hillebrand"
title: "„Weil ich glaube, die wenigsten wollen überhaupt in die Forschung gehen … “"
subtitle: "Entwicklung der aktuellen Studienordnungen am IBI"
abstract: "In den letzten zwei Jahren veröffentlichte das Institut für Bibliotheks- und Informationswissenschaft (IBI) zwei neue Studienordnungen, einmal für den Bachelorstudiengang Bibliotheks- und Informationswissenschaft, einmal für den Master Information Science. Dieser Artikel referiert die Argumente und Überlegungen am Institut zur Konzeption neuer Studienordnungen und beschreibt die begleitende Umfrage unter und Fokusgruppen mit Studierenden."
urn: "urn:nbn:de:kobv:11-110-18452/20341-5"
date: 2018-11-10
comments: false
sharing: true
footer: true

---