---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Martine Weil"
- "Erika Werner"
title: "Studierende, Bücher und Praxis"
subtitle: "Das Projektseminar "Von der Idee zum Buch" feiert sein 15-jähriges Jubiläum. Ein Interview mit Dr. Petra Hauke"
pdf: "master.pdf"
date: 2018-11-10
comments: false
sharing: true
footer: true

---