---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Ben Kaden"
- "Karsten Schuldt"
title: "Bibliographie Geschichte der Berliner und restlichen deutschsprachigen Bibliothekswissenschaft (1946–2018)"
pdf: "../master.pdf"
date: 2018-11
comments: false
sharing: true
footer: true

---