---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "34"
year: "2018"
contributor: 
- "Karsten Schuldt"
title: "Zu disparat als Debattenbeitrag"
subtitle: "Rezension zu: Schöpfel, Joachim ; Herb, Ulrich (edit.). Open Divide: Critical Studies on Open Access. Sacramento, CA: Library Juice Press, 2018"
pdf: "master.pdf"
date: 2018-11-10
comments: false
sharing: true
footer: true

---